### ISSUE TITLE
Invalid Channel

### ISSUE THREAD

**Issue by SevereOverfl0w** [snoe/clj-refactor.nvim#2]
```
Tue Feb 09 2016 15:59:18 GMT+0000 (GMT) clj-refactor.js: hello refactor
Tue Feb 09 2016 15:59:18 GMT+0000 (GMT) clj-refactor.js: transforming #object[cljs.core.async.impl.channels.ManyToManyChannel]
Tue Feb 09 2016 15:59:19 GMT+0000 (GMT) clj-refactor.js: zip-it [Error: Invalid token: :, on line: 485, on column: 19] Error: Invalid token: :, on line: 485, on column: 19
    at Error (native)
    at Function.cljs.extended.reader.reader_error.cljs$core$IFn$_invoke$arity$variadic (/home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:1840:141)
    at cljs.extended.reader.reader_error (/home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:1839:227)
    at cljs.extended.reader.read_keyword (/home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:1871:392)
    at rewrite_clj.parser.keyword.parse_keyword (/home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:2319:404)
    at rewrite_clj.reader.read_with_meta (/home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:1962:163)
    at rewrite_clj.parser.core.parse_next (/home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:2339:89)
    at /home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:2324:832
    at /home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:1963:437
    at /home/dominic/.config/nvim/plugged/clj-refactor.nvim/rplugin/node/clj-refactor.js:902:199
```

Nothing works for me, first doesn't throw an error, subsequent calls display error:
```E475: Invalid argument: Channel doesn't exist```

**Comment by snoe** [comment]
It looks like the rewrite-cljs library I'm using doesn't like a `:,` keyword in your file. I'm not sure I can help that, but the plugin should now echo the error to vim and keep working. Let me know if that works.

**Comment by SevereOverfl0w** [comment]
I'm going to give this a go now! (If I can find the file I was using it
against..)

I have been using it successfully with other files. I'd be interested to
find out what the problem is in the file.

**Comment by SevereOverfl0w** [comment]
Parse error was successfully caught, and it gave me the exact location, error was this:

```(->> {:select [:%count.*]```

I'll take a look in rewrite-cljs issues.

**Comment by SevereOverfl0w** [comment]
Moved issue upstream
